import type { DirectorPreset, CinematographerPreset } from "@/types/pipeline"

// === DIRECTOR PRESETS ===
export const BUILTIN_DIRECTOR_PRESETS: DirectorPreset[] = [
  {
    id: "deakins-naturalism",
    name: "Deakins Naturalism",
    description: "Organic staging, motivated camera, emotional truth over spectacle",
    builtIn: true,
    dramaticDensity: "balanced",
    pacingStyle: "slow-burn",
    emotionalFocus: "Internal conflict, quiet tension, unspoken subtext",
    keyframePolicy: "story_turns",
    actorDirection: "Restraint. Let silences breathe. Micro-expressions over grand gestures.",
    shotCountRange: [4, 8],
  },
  {
    id: "kubrick-precision",
    name: "Kubrick Precision",
    description: "Geometric compositions, symmetry, cold analytical gaze",
    builtIn: true,
    dramaticDensity: "lean",
    pacingStyle: "rhythmic",
    emotionalFocus: "Alienation, control, the uncanny in mundane",
    keyframePolicy: "opening_anchor",
    actorDirection: "Mechanical precision. Flat affect masking inner turmoil. Stare through the lens.",
    shotCountRange: [3, 6],
  },
  {
    id: "villeneuve-epic",
    name: "Villeneuve Epic",
    description: "Vast scale, dwarfing human figures, existential weight",
    builtIn: true,
    dramaticDensity: "dense",
    pacingStyle: "slow-burn",
    emotionalFocus: "Awe, dread, the sublime, human insignificance",
    keyframePolicy: "every_major_shift",
    actorDirection: "Bodies react to space. Small gestures against vast environments. Gravity in every step.",
    shotCountRange: [5, 10],
  },
  {
    id: "handheld-realism",
    name: "Handheld Realism",
    description: "Vérité energy, documentary intimacy, raw immediacy",
    builtIn: true,
    dramaticDensity: "dense",
    pacingStyle: "staccato",
    emotionalFocus: "Urgency, authenticity, visceral presence",
    keyframePolicy: "every_major_shift",
    actorDirection: "Overlap dialogue. Improvise blocking. Let chaos find the frame.",
    shotCountRange: [6, 12],
  },
]

// === CINEMATOGRAPHER PRESETS ===
export const BUILTIN_CINEMATOGRAPHER_PRESETS: CinematographerPreset[] = [
  {
    id: "deakins-available-light",
    name: "Deakins Available Light",
    description: "Natural sources, motivated practicals, painterly shadows",
    builtIn: true,
    defaultShotSize: "medium close-up",
    lensPreference: "40mm, shallow DOF",
    lightingPhilosophy: "Motivated sources only. One key, minimal fill. Let shadows tell the story.",
    compositionRules: ["Rule of thirds", "Leading lines", "Negative space for tension"],
    colorPalette: "Warm tungsten, desaturated mid-tones, deep blacks",
    cameraMovement: "Slow dolly, imperceptible push-ins, locked-off for confrontation",
    continuityStrictness: "standard",
    textRichness: "rich",
    relationMode: "balanced",
  },
  {
    id: "neon-noir",
    name: "Neon Noir",
    description: "High contrast, saturated practicals, rain-slicked reflections",
    builtIn: true,
    defaultShotSize: "close-up",
    lensPreference: "35mm anamorphic, lens flares",
    lightingPhilosophy: "Hard neon sources. Colored gels. Wet surfaces for reflections. No fill light.",
    compositionRules: ["Dutch angles sparingly", "Silhouettes", "Frame within frame"],
    colorPalette: "Cyan and magenta neons, deep teal shadows, blown-out highlights",
    cameraMovement: "Steadicam stalking, whip pans on reveals, static for dread",
    continuityStrictness: "flexible",
    textRichness: "lush",
    relationMode: "explicit",
  },
  {
    id: "golden-hour-natural",
    name: "Golden Hour Natural",
    description: "Magic hour warmth, backlit halos, pastoral softness",
    builtIn: true,
    defaultShotSize: "medium shot",
    lensPreference: "50mm, open aperture, soft diffusion",
    lightingPhilosophy: "Backlight everything. Golden rim light. Soft bounce for faces. No harsh shadows.",
    compositionRules: ["Center framing for intimacy", "Horizon at lower third", "Sun in frame"],
    colorPalette: "Amber, honey gold, soft greens, warm skin tones",
    cameraMovement: "Handheld breathing, slow tracking alongside characters, crane for reveals",
    continuityStrictness: "standard",
    textRichness: "rich",
    relationMode: "balanced",
  },
  {
    id: "studio-glamour",
    name: "Studio Glamour",
    description: "Classic Hollywood three-point lighting, polished perfection",
    builtIn: true,
    defaultShotSize: "medium close-up",
    lensPreference: "85mm portrait, crisp bokeh",
    lightingPhilosophy: "Three-point setup. Butterfly key for glamour. Hair light for separation. Controlled.",
    compositionRules: ["Classical center composition", "Clean backgrounds", "Eye-level camera"],
    colorPalette: "Rich blacks, creamy skin tones, silver accents, controlled contrast",
    cameraMovement: "Dolly in for emphasis, locked-off master shots, smooth pan for reveals",
    continuityStrictness: "strict",
    textRichness: "simple",
    relationMode: "minimal",
  },
]

// === DEFAULT PRESETS ===
export const DEFAULT_DIRECTOR_PRESET = BUILTIN_DIRECTOR_PRESETS[0]
export const DEFAULT_CINEMATOGRAPHER_PRESET = BUILTIN_CINEMATOGRAPHER_PRESETS[0]
